### ISSUE TITLE
Time Elapsed

### ISSUE THREAD

**Issue by BrunoTeixeira1996** [stapelberg/rsyncparse#1]
Hi @stapelberg ,
Thanks for this parser, I am currently using this to help me display a grafana dashboard. However I wanted to know if it is possible to use some sort of rsync flag to know exactly how much time the rsync lasted in order to pass that metric to https://github.com/stapelberg/rsyncprom and then display in my grafana dashboard.

**Comment by stapelberg** [comment]
No, I don’t think the rsync output contains the elapsed time.

Instead, you’ll need to separately keep track of how long the rsync process took that you started.
